# -*- coding: utf-8 -*-
"""LineaTelefonica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6t3tPX4PRFCGlPromC7Qhe5gPXv9KVZ

# Explicación Matemática

La cadena de Markov ahora tiene 3 estados:

- `0 = Línea libre`
- `1 = Línea ocupada`
- `2 = Llamada en espera`

---

# Matriz de Transición

La matriz de transición del sistema es:

\[
P =
\begin{bmatrix}
1-\alpha & \alpha & 0 \\
\beta & 1-\alpha-\beta & \alpha \\
0 & \beta & 1-\beta
\end{bmatrix}
\]

Donde:

- `α` representa la probabilidad de llegada de una llamada.
- `β` representa la probabilidad de finalización de una llamada.

---

# Interpretación de los Estados

## Estado 0 → Línea libre

La línea puede:

- Permanecer libre.
- Recibir una llamada y pasar al estado ocupado.

---

## Estado 1 → Línea ocupada

La línea puede:

- Liberarse si termina la llamada.
- Permanecer ocupada.
- Recibir otra llamada y pasar al estado de llamada en espera.

---

## Estado 2 → Llamada en espera

En este estado existen:

- Una llamada activa.
- Otra llamada esperando.

Cuando termina la llamada activa:

- La llamada en espera toma el lugar de la llamada principal.
- El sistema regresa al estado ocupado (`1`).

---

# Ejemplo Conceptual

Una secuencia posible de estados es:

```text
0 → 1 → 2 → 2 → 1 → 0
"""

import random

"""**Parámetros del modelo**"""

alpha = 0.3 # Probabilidad de que entre una llamada
beta = 0.4 # Probabilidad de que termine una llamada

# Número de pasos
n_pasos = 50

# Estados:
# 0 = Libre
# 1 = Ocupado

estado = 0 # Estado inicial

# Guardar historial
historial = [estado]

# Contadores
tiempo_libre = 0
tiempo_ocupado = 0

"""**Simulación**"""

for i in range(n_pasos):

    r = random.random()

    # Si está libre
    if estado == 0:

        # Entra llamada
        if r < alpha:
            estado = 1

        # Sigue libre
        else:
            estado = 0

    # Si está ocupado
    elif estado == 1:

        # Termina llamada
        if r < beta:
            estado = 0

        # Sigue ocupado
        else:
            estado = 1

    # Guardar estado
    historial.append(estado)

    # Contar tiempos
    if estado == 0:
        tiempo_libre += 1
    else:
        tiempo_ocupado += 1

"""**Porcentajes**"""

porcentaje_libre = (tiempo_libre / n_pasos) * 100
porcentaje_ocupado = (tiempo_ocupado / n_pasos) * 100

"""**Resultados**


"""

print("Historial de estados:")
print(historial)

print("\nTiempo libre:", tiempo_libre)
print("Tiempo ocupado:", tiempo_ocupado)

print("\nPorcentaje libre:", porcentaje_libre, "%")
print("Porcentaje ocupado:", porcentaje_ocupado, "%")